kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: dev
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      namespace: dev
      name: config-server
      labels:
        app: config-server
    spec:
      initContainers:
        - name: init
          image: registry.mouse.center:1443/glowroot:0.13.6
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /glowroot/* /agent/" ]
          volumeMounts:
            - mountPath: /agent
              name: agent
      containers:
        - name: config-server
          image: registry.mouse.center:1443/config-server
          imagePullPolicy: Always
          command: ["bash", "-c", "ls -l /agent"]
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/agent/glowroot-agent.jar -Dglowroot.collector.address=glowroot-central:8181"
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - mountPath: /agent
              name: agent
      volumes:
        - name: agent
          emptyDir:
            {}