kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: dev
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      namespace: dev
      name: config-server
      labels:
        app: config-server
    spec:
      initContainers:
        - name: init
          image: registry.mouse.center:1443/curlimages/curl
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent/* /agent/" ]
          volumeMounts:
            - mountPath: /agent
              name: agent
      containers:
        - name: config-server
          image: registry.mouse.center:1443/config-server
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/agent/skywalking-agent.jar"
            - name: SW_AGENT_NAME
              value: config-service
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: apm-backend:11800
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - mountPath: /agent
              name: agent
      volumes:
        - name: agent
          emptyDir:
            {}
        - name: agent-file
          nfs:
            path: /volume2/k8s/skywalking
            server: nas