kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 80
      targetPort: 8080
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: dev
  name: config-service-cfg
data:
  server.port: '8080'
  spring.cloud.config.server.bootstrap: 'true'
  spring.cloud.config.server.git.url: 'https://scm.mouse.center:1443/mouse/config.git'
  spring.cloud.config.server.git.username: 'config'
  spring.cloud.config.server.git.password: 'Ab12345678'
  spring.cloud.config.server.git.default-label: 'master'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: dev
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      namespace: dev
      name: config-server
      labels:
        app: config-server
    spec:
      initContainers:
        - name: glowroot
          image: registry.mouse.center:1443/glowroot:0.13.6
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /glowroot /agent/glowroot" ]
          volumeMounts:
            - mountPath: /agent
              name: agent
        - name: skywalking
          image: registry.mouse.center:1443/apache/skywalking-java-agent:8.8.0-java17
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /agent/skywalking" ]
          volumeMounts:
            - mountPath: /agent
              name: agent
      containers:
        - name: config-server
          image: registry.mouse.center:1443/config-server
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/agent/glowroot/glowroot.jar -Dglowroot.collector.address=glowroot-central:8181 -javaagent:/agent/skywalking/skywalking-agent.jar"
            - name: SW_AGENT_NAME
              value: "config-server"
            - name: SW_AGENT_NAMESPACE
              value: "dev"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking-backend:11800"
          envFrom:
            - configMapRef:
                name: config-service-cfg
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - mountPath: /agent
              name: agent
      volumes:
        - name: agent
          emptyDir:
            {}
