kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: dev
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      namespace: dev
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: registry.mouse.center:1443/config-server
          imagePullPolicy: Always
          command:
            - bash
            - -c
            - "java -javaagent:/apps/glowroot/glowroot.jar -Dglowroot.collector.address=https://glowroot.api.mouse.center -jar /apps/app.jar"
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
