apiVersion: v1
kind: ConfigMap
metadata:
  name: glowroot-central-cfg
  namespace: dev
data:
  "glowroot-central.properties": |
    cassandra.contactPoints=cassandra.db
    cassandra.port=
    cassandra.username=
    cassandra.password=
    cassandra.ssl=
    cassandra.keyspace=
    cassandra.consistencyLevel=
    cassandra.maxConcurrentQueries=
    cassandra.gcGraceSeconds=
    grpc.bindAddress=
    grpc.httpPort=
    grpc.httpsPort=
    ui.bindAddress=
    ui.port=
    ui.https=
    ui.contextPath=
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: glowroot-central
  namespace: dev
spec:
  selector:
    matchLabels:
      app: glowroot-central
  template:
    metadata:
      namespace: dev
      name: glowroot-central
      labels:
        app: glowroot-central
    spec:
      containers:
        - name: glowroot-central
          image: registry.mouse.center:1443/glowroot-central:0.13.6
          ports:
            - containerPort: 4000
              name: web
              protocol: TCP
            - containerPort: 8181
              name: control
              protocol: TCP
          volumeMounts:
            - mountPath: /glowroot-central/glowroot-central.properties
              name: glowroot-central-cfg
              subPath: glowroot-central.properties
      volumes:
        - name: glowroot-central-cfg
          configMap:
            name: glowroot-central-cfg
---
kind: Service
apiVersion: v1
metadata:
  name: glowroot-central
  namespace: dev
spec:
  selector:
    app: glowroot-central
  ports:
    - port: 80
      name: web
      targetPort: 4000
    - port: 8181
      name: api
      targetPort: 8181
    - port: 9042
      name: db
      targetPort: 9042

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glowroot-central-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
    - host: apm.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glowroot-central
                port:
                  name: web