kind: Deployment
apiVersion: apps/v1
metadata:
  name: glowroot-central
  namespace: dev
spec:
  selector:
    matchLabels:
      app: glowroot-central
  template:
    metadata:
      namespace: dev
      name: glowroot-central
      labels:
        app: glowroot-central
    spec:
      containers:
        - name: glowroot-central
          image: registry.mouse.center:1443/glowroot/glowroot-central:0.14.0-beta
          ports:
            - containerPort: 4000
              name: web
              protocol: TCP
            - containerPort: 8181
              name: control
              protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: glowroot-central
  namespace: dev
spec:
  selector:
    app: glowroot-central
  ports:
    - port: 80
      name: web
      targetPort: 4000
    - port: 8181
      name: central
      targetPort: 8181

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glowroot-central-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: glowroot.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glowroot-central
                port:
                  name: web
