apiVersion: "storageos.com/v1"
kind: StorageOSCluster
metadata:
  name: "storageos-cluster"
  namespace: "storageos-operator"
spec:
  # StorageOS Pods are in kube-system by default
  secretRefName: "storageos-api" # Reference from the Secret created in the previous step
  secretRefNamespace: "storageos-operator"  # Namespace of the Secret
  k8sDistro: "upstream"
  images:
    nodeContainer: "storageos/node:v2.3.0" # StorageOS version
    kubeSchedulerContainer: "k8s.gcr.io/kube-scheduler:v1.18.8"
  kvBackend:
    address: 'storageos-etcd-client.storageos-etcd:2379' # Example address, change for your etcd endpoint
    csi:
      enable: true
      deploymentStrategy: "deployment"
      enableProvisionCreds: true
      enableControllerPublishCreds: true
      enableNodePublishCreds: true
      enableControllerExpandCreds: true
  nodeSelectorTerms:
    - matchExpressions:
        - key: "node-role.kubernetes.io/worker"
          operator: In
          values:
            - "true"