FROM curlimages/curl as build

WORKDIR /home/curl_user

ENV URL_PREFIX=https://registry.mouse.center:1443/repository/raw-group

RUN curl -LO  "$URL_PREFIX/openjdk/OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz"
RUN tar -zxvf OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz

RUN curl -LO "$URL_PREFIX/gradle/gradle-7.1.1.tar.gz"
RUN tar -zxvf gradle-7.1.1.tar.gz


FROM gocd/gocd-agent-centos-7:v21.1.0

USER root

RUN yum install epel-release -y && yum install -y nodejs docker-client

COPY --from=build /home/curl_user/jdk-14.0.2+12 /opt/java/jdk-14.0.2+12
COPY --from=build /home/curl_user/gradle-7.1.1 /opt/gradle/gradle-7.1.1

RUN ls -l /opt/java \
 && ls -l /opt/gradle

ENV GRADLE_HOME=/opt/gradle/gradle-7.1.1
ENV JAVA_HOME=/opt/java/jdk-14.0.2+12
ENV TZ=Asia/Shanghai
ENV GRADLE_VERSION=7.1.1

RUN ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle \
  && gradle --version \
  && ln --symbolic "${GRADLE_HOME}/bin/java" /usr/bin/java \
  && java --version \
  && node -v
