FROM curlimages/curl as build

WORKDIR /home/curl_user

ENV URL_PREFIX=https://registry.mouse.center:1443/repository/raw-group

RUN curl -LO  "$URL_PREFIX/openjdk/openjdk-17.0.1_linux-x64_bin.tar.gz"
RUN tar -zxvf openjdk-17.0.1_linux-x64_bin.tar.gz


FROM gocd/gocd-agent-centos-7:v21.3.0
USER root

COPY --from=build /home/curl_user/jdk-17.0.1 $JAVA_HOME
RUN  ln --symbolic "${JAVA_HOME}/bin/java" /usr/bin/java \
  && java --version

RUN yum install epel-release -y && yum install -y docker-client && yum install -y maven
ENV JAVA_HOME=/opt/java/jdk-17.0.1
ENV TZ=Asia/Shanghai
