FROM curlimages/curl
USER root
WORKDIR /home/curl_user

RUN curl -LO https://registry.mouse.center:1443/repository/raw-hosted/jq/jq-linux64

RUN chmod +x jq-linux64 && mv jq-linux64 /jq

COPY ./cleanup.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh
RUN chmod 755 /jq

ENTRYPOINT ["sh" "/entrypoint.sh"]