FROM gocd/gocd-agent-centos-7:v21.3.0
USER root

ENV TZ=Asia/Shanghai
RUN curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
RUN yum install epel-release -y && yum install -y docker-client && yum install nodejs -y