apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "dashboard.k8s.mouse.center"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              serviceName: serviceName:kubernetes-dashboard
              servicePort: 443