apiVersion: v1
kind: ConfigMap
metadata:
  name: application-cfg
  namespace: app
data:
  application.yaml: |
    spring:
      config:
        import: optional:configserver:http://config-server.app

