apiVersion: v1
kind: ConfigMap
metadata:
  name: application-test-cfg
  namespace: app
data:
  spring.config.import: optional:configserver:http://config-server.app
  spring.cloud.config.profile: test
  spring.cloud.config.fail-fast: 'true'
  spring.profiles.active: test
