---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: app
  name: home-assistant-macvlan
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "home-assistant-macvlan",
      "type": "ipvlan",
      "master": "ens192",
      "capabilities": {"ips": true},
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.10.60/24",
                "gateway": "192.168.10.1"
            }
        ],
      }
    }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: app
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: home-assistant-macvlan
      namespace: app
      name: home-assistant
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: registry.mouse.center:1443/linuxserver/homeassistant
          imagePullPolicy: Always
          ports:
            - containerPort: 8123
              name: http
              protocol: TCP
            - containerPort: 21064
              name: homekit
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          env:
            - name: http_proxy
              value: "http://win10:7890"
            - name: https_proxy
              value: "http://win10:7890"
            - name: all_proxy
              value: "socks5://win10:7890"
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          nfs:
            path: /volume2/k8s/home-assistant/config
            server: nas
---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: app
spec:
  selector:
    app: home-assistant
  ports:
    - port: 80
      name: web
      targetPort: http
---
kind: Service
apiVersion: v1
metadata:
  name: homekit
  namespace: app
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
    - port: 21064
      name: homekit-tcp
      nodePort: 30064
      targetPort: 21064
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
    - host: iot.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  name: web
