apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: app
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      namespace: app
      name: home-assistant
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: registry.mouse.center:1443/homeassistant/home-assistant
          ports:
            - containerPort: 8123
              name: http
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          env:
            - name: http_proxy
              value: "http://win10:7890"
            - name: https_proxy
              value: "http://win10:7890"
            - name: all_proxy
              value: "socks5://win10:7890"
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          nfs:
            path: /volume2/k8s/home-assistant/config
            server: nas
---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: app
spec:
  selector:
    app: home-assistant
  ports:
    - port: 80
      name: web
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: iot.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  name: web
