apiVersion: batch/v1
kind: Job
metadata:
  name: jd-assistant
  namespace: app
  labels:
    jobgroup: jd-assistant
spec:
  template:
    metadata:
      name: jd-assistant
      labels:
        jobgroup: jd-assistant
    spec:
      restartPolicy: Never
      containers:
        - name: jd-assistant
          image: docker-repository.mouse.center:1443/jd-assistant
          volumeMounts:
            - mountPath: /etc/jd-assistant/main.py
              name: cfg
              subPath: main.py
            - mountPath: /etc/jd-assistant/cookies/user.cookies
              name: cfg
              subPath: user.cookies
            - mountPath: /etc/jd-assistant/config.ini
              name: cfg
              subPath: config.ini
      volumes:
        - name: cfg
          configMap:
            name: jd-assistant-cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jd-assistant-cfg
  namespace: app
data:
  main.py: |
    import time
    from exception import AsstException
    from jd_assistant import Assistant

    if __name__ == '__main__':
        asst = Assistant()
        time.sleep(60)
        if not asst.is_login:
            raise AsstException('未登陆')
        asst.add_item_to_cart(sku_ids='100004187691')
  user.cookies: |
    <80>^D<95>f
    ^@^@^@^@^@^@<8c>^Prequests.cookies<94><8c>^QRequestsCookieJar<94><93><94>)<81><94>}<94>(<8c>^G_policy<94><8c>^Nhttp.cookiejar<94><8c>^SDefaultCookiePolicy<94><93><94>)<81><94>}<94>(<8c>^Hnetscape<94><88><8c>^Grfc2965<94><89><8c>^Srfc2109_as_netscape<94>N<8c>^Lhide_cookie2<94><89><8c>^Mstrict_domain<94><89><8c>^[strict_rfc2965_unverifiable<94><88><8c>^Vstrict_ns_unverifiable<94><89><8c>^Pstrict_ns_domain<94>K^@<8c>^\strict_ns_set_initial_dollar<94><89><8c>^Rstrict_ns_set_path<94><89><8c>^Psecure_protocols<94><8c>^Ehttps<94><8c>^Cwss<94><86><94><8c>^P_blocked_domains<94>)<8c>^P_allowed_domains<94>N<8c>^D_now<94>J[i6`ub<8c>^H_cookies<94>}<94>(<8c>^Opassport.jd.com<94>}<94><8c>^A/<94>}<94>(<8c>^Calc<94>h^F<8c>^FCookie<94><93><94>)<81><94>}<94>(<8c>^Gversion<94>K^@<8c>^Dname<94>h"<8c>^Evalue<94><8c>^XmkHD5zYtI2RjH+DLmN8v9w==<94><8c>^Dport<94>N<8c>^Nport_specified<94><89><8c>^Fdomain<94>h^^<8c>^Pdomain_specified<94><89><8c>^Rdomain_initial_dot<94><89><8c>^Dpath<94>h <8c>^Npath_specified<94><88><8c>^Fsecure<94><89><8c>^Gexpires<94>N<8c>^Gdiscard<94><88><8c>^Gcomment<94>N<8c>^Kcomment_url<94>N<8c>^Grfc2109<94><89><8c>^E_rest<94>}<94><8c>^HHttpOnly<94>Nsub<8c>^B_t<94>h$)<81><94>}<94>(h'K^@h(h;h)<8c>,aAGa2x95Ao6e+wwn+iCt9/3wkwy9WXJJ3G/Vb2taxWY=<94>h+Nh,<89>h-<8c>^Opassport.jd.com<94>h.<89>h/<89>h0h h1<88>h2<89>h3Nh4<88>h5Nh6Nh7<89>h8}<94>ub<8c>    DeviceSeq<94>h$)<81><94>}<94>(h'K^@h(hAh)<8c> 73b48896a97c41179af93aaa15c569fa<94>h+Nh,<89>h-<8c>^Opassport.jd.com<94>h.<89>h/<89>h0h h1<88>h2<89>h3J[·#ah4<89>h5Nh6Nh7<89>h8}<94><8c>^HHttpOnly<94>Nsubus<8c>^Kqr.m.jd.com<94>}<94>h }<94><8c> QRCodeKey<94>h$)<81><94>}<94>(h'K^@h(hKh)<8c>0AAEAIB_2W8wv8TxajH4dAY2hEnG6tGdpMRzkJBjOORq1y0Qq<94>h+Nh,<89>h-hHh.<89>h/<89>h0h h1<89>h2<89>h3Nh4<88>h5Nh6Nh7<89>h8}<94><8c>^HHttpOnly<94>Nsubss<8c>^G.jd.com<94>}<94>h }<94>(<8c>^Kwlfstk_smdl<94>h$)<81><94>}<94>(h'K^@h(hTh)<8c> 1rilltdj610yitonislr35cds5t29kmb<94>h+Nh,<89>h-hQh.<88>h/<88>h0h h1<88>h2<89>h3Nh4<88>h5Nh6Nh7<89>h8}<94>ub<8c>^GTrackID<94>h$)<81><94>}<94>(h'K^@h(hYh)<8c>l13Q9NNJZCbHcrzoyBlJHpXcY6y6vsKIHgqhm05y2MkDe8NsMVwheTcajt4jjmSVFv4A373Xri--Vv9TevnxCWXODcCxXGcNRuT9y22m2vNe4<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3JÛj<9c>ih4<89>h5Nh6Nh7<89>h8}<94>ub<8c>^Dthor<94>h$)<81><94>}<94>(h'K^@h(h_h)X ^A^@^@7718535A87D6A71189ACEA56F114E740A21DCDCAED42EA9914632CA5C8A6E6A307CF025BFBBDCFB7A26D5A30F8B438D00AF3A438FDCEC06D731E53649DF75E57CA12CD6FE607DD9BBCA20364063B60DC55A92828C9D55FD9D672C7120B2EDCF75EEEC16EFC64F3F419D3456B885B1CAC0F4A58E0F18759D12C16BCD17F0ED8554A1E111CCD57A2255138B79B9E503566<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3Nh4<88>h5Nh6Nh7<89>h8}<94><8c>^HHttpOnly<94>Nsub<8c>^EpinId<94>h$)<81><94>}<94>(h'K^@h(hfh)<8c>^VQYpbleQHgjslVTi6piQX-Q<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3JÛ<9c>^Wbh4<89>h5Nh6Nh7<89>h8}<94>ub<8c>^Cpin<94>h$)<81><94>}<94>(h'K^@h(hlh)<8c>^M15156971863_p<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3J[ö]`h4<89>h5Nh6Nh7<89>h8}<94>ub<8c>^Eunick<94>h$)<81><94>}<94>(h'K^@h(hrh)<8c>-%E5%B0%8F%E9%B8%A1%E7%9A%84%E6%95%91%E5%85%B5<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3J[ö]`h4<89>h5Nh6Nh7<89>h8}<94><8c>^HHttpOnly<94>Nsub<8c>
    ceshi3.com<94>h$)<81><94>}<94>(h'K^@h(hyh)<8c>^C201<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3Nh4<88>h5Nh6Nh7<89>h8}<94>ub<8c>^C_tp<94>h$)<81><94>}<94>(h'K^@h(h^?h)<8c>^^LxLwvwxCNGyqTfHC1Db%2FWA%3D%3D<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3J[ö]`h4<89>h5Nh6Nh7<89>h8}<94>ub<8c>^Hlogining<94>h$)<81><94>}<94>(h'K^@h(h<85>h)<8c>^A1<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3Nh4<88>h5Nh6Nh7<89>h8}<94>ub<8c>^D_pst<94>h$)<81><94>}<94>(h'K^@h(h<8b>h)<8c>^M15156971863_p<94>h+Nh,<89>h-<8c>^G.jd.com<94>h.<88>h/<88>h0h h1<88>h2<89>h3J[ö]`h4<89>h5Nh6Nh7<89>h8}<94><8c>^HHttpOnly<94>Nsubusuh^[J[i6`ub.
  config.ini: |
    [account]
    payment_pwd =

    [config]
    eid = YH3NQBJ3OUWBAHU66GRVMAF7S42ZEUDIKROIIYZK7ZWWLBPVI3ZGEMPNBDTOCUUSEDWQH335T43OUIONK47EOZR3MQ
    fp = e03e8102e8cd4713ece04fc2879f0122
    track_id = TestTrackId
    risk_control = TestTrackId
    timeout =
    random_useragent = false

    [messenger]
    enable = false
    sckey =
