kind: Deployment
apiVersion: apps/v1
metadata:
  name: jd-assistant
  namespace: app
  labels:
    k8s-app: jd-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jd-assistant
  template:
    spec:
      containers:
        - name: jd-assistant
          image: docker-repository.mouse.center:1443/jd-assistant
          volumeMounts:
            - mountPath: /etc/jd-assistant/main.py
              name: main-py
              subPath: main.py
      volumes:
        - name: main-py
          configMap:
            name: jd-assistant-cfg
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jd-assistant-cfg
  namespace: app
data:
  main.py: |
    from jd_assistant import Assistant

    if __name__ == '__main__':
      sku_ids = '100015042086'  # 商品id
      asst = Assistant()  # 初始化
      asst.login_by_QRcode()  # 扫码登陆
      asst.add_item_to_cart(sku_ids)
      asst.exec_seckill_by_time(sku_ids=sku_ids, buy_time='2021-01-14 11:00:00.000', retry=10, interval=0.01)
