apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxgsm
  namespace: app
spec:
  selector:
    matchLabels:
      app: linuxgsm
  template:
    metadata:
      name: app
      labels:
        app: linuxgsm
    spec:
      containers:
        - name: arkserver
          image: registry.mouse.center:1443/linuxgsm
          command:
            - arkserver
            - start
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
              name: game
            - containerPort: 7778
              name: raw
            - containerPort: 27015
              name: query
            - containerPort: 27020
              name: rcon
          livenessProbe:
            tcpSocket:
              port: 27020
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 27020
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 10
          volumeMounts:
            - mountPath: /app/
              name: lgsm
          resources:
            limits:
              memory: 8Gi
      volumes:
        - name: lgsm
          nfs:
            path: /volume2/k8s/linuxgsm
            server: nas

---
kind: Service
apiVersion: v1
metadata:
  name: linuxgsm
  namespace: app
spec:
  type: NodePort
  selector:
    app: linuxgsm
  ports:
    - port: 7777
      targetPort: 7777
      nodePort: 30777
      name: game
    - port: 7778
      targetPort: 7778
      nodePort: 30778
      name: raw
    - port: 27015
      targetPort: 27015
      nodePort: 30015
      name: query
    - port: 27020
      targetPort: 27020
      nodePort: 30020
      name: rcon
