apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxgsm
  namespace: app
spec:
  selector:
    matchLabels:
      app: linuxgsm
  template:
    metadata:
      name: app
      labels:
        app: linuxgsm
    spec:
      containers:
        - name: arkserver
          image: registry.mouse.center:1443/linuxgsm
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
              name: game
              protocol: UDP
            - containerPort: 7778
              name: raw
            - containerPort: 27015
              name: query
              protocol: UDP
            - containerPort: 27020
              name: rcon
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 27020
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 27020
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 10
          volumeMounts:
            - mountPath: /app/
              name: lgsm
            - mountPath: /home/linuxgsm/.steam
              name: steam
              subPath: steam
            - mountPath: /home/linuxgsm/.local
              name: steam
              subPath: local
          resources:
            limits:
              memory: 8Gi
      volumes:
        - name: lgsm
          nfs:
            path: /volume2/k8s/linuxgsm
            server: nas
        - name: steam
          nfs:
            path: /volume2/k8s/linuxgsm/steam
            server: nas
---
kind: Service
apiVersion: v1
metadata:
  name: linuxgsm
  namespace: app
spec:
  type: NodePort
  selector:
    app: linuxgsm
  ports:
    - port: 7777
      targetPort: 7777
      nodePort: 30777
      name: game
      protocol: UDP
    - port: 7778
      targetPort: 7778
      nodePort: 30778
      name: raw
      protocol: UDP
    - port: 27015
      targetPort: 27015
      nodePort: 30015
      name: query
      protocol: UDP
    - port: 27020
      targetPort: 27020
      nodePort: 30020
      name: rcon
      protocol: TCP

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: check-update
  namespace: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: registry.mouse.center:1443/kubectl
              command:
                - kubeexec
                - app
                - linuxgsm
                - "arkserver force-update"
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube
                  subPath: config
          volumes:
            - name: kube
              secret:
                secretName: kubectl-secret
  schedule: "0 4 * * *"

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: linuxgsm-monitor
  namespace: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: registry.mouse.center:1443/kubectl
              command:
                - kubeexec
                - app
                - linuxgsm
                - "arkserver m"
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube
                  subPath: config
          volumes:
            - name: kube
              secret:
                secretName: kubectl-secret
  schedule: "*/5 * * * *"

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: linuxgsm-check-update
  namespace: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: registry.mouse.center:1443/kubectl
              command:
                - kubeexec
                - app
                - linuxgsm
                - "arkserver check-update"
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube
                  subPath: config
          volumes:
            - name: kube
              secret:
                secretName: kubectl-secret
  schedule: "*/30 * * * *"

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: linuxgsm-update
  namespace: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: registry.mouse.center:1443/kubectl
              command:
                - kubeexec
                - app
                - linuxgsm
                - "arkserver update"
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube
                  subPath: config
          volumes:
            - name: kube
              secret:
                secretName: kubectl-secret
  schedule: "0 4 * * *"

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: linuxgsm-update-lgsm
  namespace: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: registry.mouse.center:1443/kubectl
              command:
                - kubeexec
                - app
                - linuxgsm
                - "arkserver update-lgsm"
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube
                  subPath: config
          volumes:
            - name: kube
              secret:
                secretName: kubectl-secret
  schedule: "0 0 * * 0"
