kind: Deployment
apiVersion: apps/v1
metadata:
  name: printer
  namespace: app
  labels:
    k8s-app: printer
spec:
  selector:
    matchLabels:
      k8s-app: printer
  template:
    metadata:
      namespace: app
      name: printer
      labels:
        k8s-app: printer
    spec:
      nodeSelector:
        usb.type: printer
      containers:
        - name: mainsail
          image: registry.mouse.center:1443/mainsail-crew/mainsail:v2.4.1
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: /usr/share/nginx/html/config.json
              name: mainsail
              subPath: config.json
        - name: klipper-moonraker
          image: registry.mouse.center:1443/dimalo/klipper-moonraker
          ports:
            - containerPort: 7125
              name: klipper
          volumeMounts:
            - mountPath: /home/klippy/gcode_files
              name: gcode
            - mountPath: /home/klippy/.config
              name: klipper
            - mountPath: /home/klippy/.moonraker
              name: moonraker
      volumes:
        - name: mainsail
          nfs:
            server: nas
            path: /volume2/k8s/printer/mainsail
        - name: gcode
          nfs:
            server: nas
            path: /volume2/k8s/printer/gcode
        - name: klipper
          nfs:
            server: nas
            path: /volume2/k8s/printer/klipper
        - name: moonraker
          nfs:
            server: nas
            path: /volume2/k8s/printer/moonraker
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: printer
spec:
  selector:
    k8s-app: printer
  ports:
    - port: 80
      name: web
      targetPort: web
    - port: 7125
      name: klipper
      targetPort: klipper
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: printer-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
    - host: printer.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: printer
                port:
                  name: web
