kind: Deployment
apiVersion: apps/v1
metadata:
  name: printer
  namespace: app
  labels:
    k8s-app: printer
spec:
  selector:
    matchLabels:
      k8s-app: printer
  template:
    metadata:
      namespace: app
      name: printer
      labels:
        k8s-app: printer
    spec:
      nodeSelector:
        usb.type: printer
      containers:
        - name: klipper-moonraker
          image: registry.mouse.center:1443/klipper-moonraker:20221225-1347
          ports:
            - containerPort: 7125
              name: klipper
          livenessProbe:
            tcpSocket:
              port: 7125
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          volumeMounts:
            - mountPath: /home/klippy/.config
              name: klipper
              subPath: config
            - mountPath: /home/klippy/printer_data/config
              name: klipper
              subPath: config
            - mountPath: /home/klippy/printer_data/gcodes
              name: klipper
              subPath: gcode_files
            - mountPath: /home/klippy/printer_data/logs
              name: klipper
              subPath: logs
            - mountPath: /home/klippy/printer_data/comms
              name: klipper
              subPath: comms
            - mountPath: /home/klippy/printer_data/cert
              name: klipper
              subPath: cert
            - mountPath: /home/klippy/gcode_files
              name: klipper
              subPath: gcode_files
            - mountPath: /home/klippy/.moonraker
              name: klipper
              subPath: moonraker
            - mountPath: /dev
              name: usb
        - name: fluidd
          image: registry.mouse.center:1443/dimalo/fluidd
          env:
            - name: KLIPPER_HOST
              value: printer
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
      volumes:
        - name: mainsail
          nfs:
            server: nas
            path: /volume2/k8s/printer/mainsail
        - name: klipper
          nfs:
            server: nas
            path: /volume2/k8s/printer/klipper
        - name: usb
          hostPath:
            path: /dev
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: printer
spec:
  selector:
    k8s-app: printer
  ports:
    - port: 80
      name: web
      targetPort: web
    - port: 7125
      name: klipper
      targetPort: klipper
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: printer-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: downloader-web-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: "nginx"
  rules:
    - host: printer.mouse.center
      http:
        paths:
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: printer
                port:
                  name: klipper
          - path: /
            pathType: Prefix
            backend:
              service:
                name: printer
                port:
                  name: web
