kind: Service
apiVersion: v1
metadata:
  name: reader
  namespace: app
  labels:
    app: reader
spec:
  selector:
    app: reader
  ports:
    - port: 80
      name: web
      targetPort: web

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: reader-cfg
  namespace: app
  labels:
    app: reader
data:
  SPRING_PROFILES_ACTIVE: "prod"
  READER_APP_USERLIMIT: "50" #用户上限,默认且最大值为50
  READER_APP_USERBOOKLIMIT: "20000" #用户书籍上限,默认200
  READER_APP_CACHECHAPTERCONTENT: "true" #开启缓存章节内容
  # 如果启用远程webview，需要取消注释下面的 remote-webview 服务
  # - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050 #开启远程webview
  # ↓多用户模式配置↓
  READER_APP_SECURE: "true" #开启登录鉴权，开启后将支持多用户模式
  READER_APP_SECUREKEY: "970210"  #管理员密码  建议修改
  READER_APP_INVITECODE: "Mouse" #注册邀请码 建议修改,如不需要可注释或删除
  READER_APP_DEFAULTUSERENABLEWEBDAV: "true"  # 用户是否默认启用webdav
  READER_APP_DEFAULTUSERENABLELOCALSTORE: "true" # 用户是否默认启用localStore
  READER_APP_DEFAULTUSERENABLEBOOKSOURCE: "true"  # 用户是否默认启用书源编辑
  READER_APP_DEFAULTUSERENABLERSSSOURCE: "true"   # 用户是否默认启用RSS源编辑
  READER_APP_DEFAULTUSERBOOKSOURCELIMIT: "1000000"  # 用户默认书源上限
  READER_APP_DEFAULTUSERBOOKLIMIT: "20000"    # 用户默认书籍上限
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: reader
  namespace: app
  labels:
    app: reader
spec:
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      name: reader
      namespace: app
      labels:
        app: reader
    spec:
      containers:
        - name: reader
          image: registry.mouse.center:1443/hectorqin/reader
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 60
          volumeMounts:
            - mountPath: /storage
              name: storage
            - mountPath: /logs
              name: logs
          envFrom:
            - configMapRef:
                name: reader-cfg
      volumes:
        - name: storage
          nfs:
            path: /volume2/k8s/reader/storage
            server: nas
        - name: logs
          nfs:
            path: /volume2/k8s/reader/logs
            server: nas
        - name: reader-config
---
kind: CronJob
apiVersion: batch/v1
metadata:
  namespace: app
  name: auto-upgrade-reader
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: app
          name: auto-upgrade-reader
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: registry.mouse.center:1443/kubectl
              imagePullPolicy: Always
              command:
                - kubectl
                - rollout
                - -n
                - app
                - restart
                - deployment/reader
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube
                  subPath: config
          volumes:
            - name: kube
              secret:
                secretName: kubectl-secret
  schedule: "0 5 * * *"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reader-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
    - host: reader.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reader
                port:
                  name: web
