apiVersion: batch/v1
kind: Job
metadata:
  namespace: app
  name: test
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kubectl
          image: registry.mouse.center:1443/kubectl
          command:
            - kubectl
          args:
            - exec -it -n app `kubectl get pods -n app -l app=linuxgsm | grep linuxgsm |awk '{print $1}'` -- arkserver monitor
          volumeMounts:
            - mountPath: /root/.kube/config
              name: kube
              subPath: config
      volumes:
        - name: kube
          secret:
            secretName: kubectl-secret
