apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users
  namespace: app
  labels:
    k8s-app: users
spec:
  serviceName: users
  replicas: 1
  selector:
    matchLabels:
      k8s-app: users
  template:
    metadata:
      namespace: app
      name: users
      labels:
        k8s-app: users
    spec:
      containers:
        - name: users
          image: docker-repository.mouse.center:1443/users/users
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
          envFrom:
            - configMapRef:
                name: application-test-cfg
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 6
          volumeMounts:
            - mountPath: /app/cofnig
              name: users-key
      volumes:
        - name: users-key
          nfs:
            server: 192.168.20.5
            path: /volume1/k8s/users
            readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  namespace: app
  name: users
spec:
  selector:
    k8s-app: users
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: users.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 80
