apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: web-rtc-server
spec:
  selector:
    matchLabels:
      k8s-app: web-rtc-server
  replicas: 1
  template:
    metadata:
      name: web-rtc-server
      namespace: app
      labels:
        k8s-app: web-rtc-server
    spec:
      containers:
        - name: coturn
          image: registry.mouse.center:1443/coturn/coturn
          ports:
            - containerPort: 3478
              name: turn
              protocol: TCP
            - containerPort: 3478
              name: turn-udp
              protocol: UDP
            - containerPort: 5349
              name: tls-turn
              protocol: TCP
            - containerPort: 5349
              name: tls-turn-udp
              protocol: UDP
            - containerPort: 49152
              protocol: UDP
            - containerPort: 49153
              protocol: UDP
            - containerPort: 49154
              protocol: UDP
            - containerPort: 49155
              protocol: UDP
            - containerPort: 49156
              protocol: UDP
            - containerPort: 49157
              protocol: UDP
            - containerPort: 49158
              protocol: UDP
            - containerPort: 49159
              protocol: UDP
            - containerPort: 49160
              protocol: UDP
            - containerPort: 49161
              protocol: UDP
            - containerPort: 49162
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/coturn/turnserver.conf
              name: turn-cfg
              subPath: turnserver.conf
      volumes:
        - name: turn-cfg
          nfs:
            path: /volume2/k8s/web-rtc/coturn/config
            server: nas
        - name: coturn-data
          nfs:
            path: /volume2/k8s/web-rtc/coturn/data
            server: nas

---
kind: Service
apiVersion: v1
metadata:
  name: web-rtc-server
  namespace: app
spec:
  ports:
    - port: 3478
      name: turn
      targetPort: 3478
      protocol: TCP
    - port: 3478
      name: turn-udp
      targetPort: 3478
      protocol: UDP
    - port: 5349
      name: tls-turn
      protocol: TCP
    - port: 5349
      name: tls-turn-udp
      protocol: UDP
    - port: 49152
      targetPort: 49152
      nodePort: 30152
      protocol: UDP
    - port: 49153
      targetPort: 49153
      nodePort: 30153
      protocol: UDP
    - port: 49154
      targetPort: 49154
      nodePort: 30154
      protocol: UDP
    - port: 49155
      targetPort: 49155
      nodePort: 30155
      protocol: UDP
    - port: 49156
      targetPort: 49156
      nodePort: 30156
      protocol: UDP
    - port: 49157
      targetPort: 49157
      nodePort: 30157
      protocol: UDP
    - port: 49158
      targetPort: 49158
      nodePort: 30158
      protocol: UDP
    - port: 49159
      targetPort: 49159
      nodePort: 30159
      protocol: UDP
    - port: 49160
      targetPort: 49160
      nodePort: 30160
      protocol: UDP
    - port: 49161
      targetPort: 49161
      nodePort: 30161
      protocol: UDP
    - port: 49162
      targetPort: 49162
      nodePort: 30162
      protocol: UDP