kind: PersistentVolume
apiVersion: v1
metadata:
  name: godata-pv
  namespace: cd
  labels:
    pv: godata-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/k8s/gocd/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: godata-pvc
  namespace: cd
spec:
  selector:
    matchLabels:
      pv: godata-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gohome-pv
  namespace: cd
  labels:
    pv: gohome-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/k8s/gocd/go
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gohome-pvc
  namespace: cd
spec:
  selector:
    matchLabels:
      pv: gohome-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: goworkingdir-pv
  namespace: cd
  labels:
    pv: goworkingdir-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/k8s/gocd/working
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: goworkingdir-pvc
  namespace: cd
spec:
  selector:
    matchLabels:
      pv: goworkingdir-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gocd
  namespace: cd
  labels:
    k8s-app: gocd
spec:
  selector:
    matchLabels:
      k8s-app: gocd
  template:
    metadata:
      name: gocd
      namespace: cd
      labels:
        k8s-app: gocd
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: gocd-server
          image: registry.mouse.center:1443/gocd-server:v21.1.0
          ports:
            - containerPort: 8153
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8153
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
          readinessProbe:
            tcpSocket:
              port: 8153
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
          volumeMounts:
            - mountPath: /godata
              name: godata
            - mountPath: /root/
              name: gohome
            - mountPath: /go-working-dir
              name: goworkingdir
      volumes:
        - name: godata
          persistentVolumeClaim:
            claimName: godata-pvc
        - name: gohome
          persistentVolumeClaim:
            claimName: gohome-pvc
        - name: goworkingdir
          persistentVolumeClaim:
            claimName: goworkingdir-pvc
---
kind: Service
apiVersion: v1
metadata:
  namespace: cd
  name: gocd
  labels:
    k8s-app: gocd
spec:
  ports:
    - port: 443
      name: https
      targetPort: 8153
  selector:
    k8s-app: gocd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gocd-ingress
  namespace: cd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: cd.mouse.center
      http:
        paths:
          - backend:
              service:
                name: gocd
                port:
                  number: 443
            path: /
            pathType: Prefix
