apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-centos7
  namespace: cd
  labels:
    app: gocd-agent
spec:
  containers:
    - name: gocd-agent-container
      image: registry.mouse.center:1443/gocd-agent-java-node-docker:java17_gradle7.2
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /root/.ssh
          name: ssh
          subPath: .ssh
        - mountPath: /root/.docker
          name: docker-config
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: docker-config
      hostPath:
        path: /root/.docker
    - name: ssh
      nfs:
        path: /volume2/k8s/gocd/go
        server: nas
