apiVersion: v1
kind: ServiceAccount
metadata:
  name: gocd-user
  namespace: cd
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gocd-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespace"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gocd-role-binding
subjects:
  - kind: ServiceAccount
    name: gocd-user
    namespace: cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gocd-role
---
kind: Secret
apiVersion: v1
metadata:
  name: gocd-user-token
  namespace: cd
  annotations:
    kubernetes.io/service-account.name: gocd-user
type: kubernetes.io/service-account-token
---
