apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cd
  name: gocd-agent-config
data:
  AGENT_AUTO_REGISTER_KEY: "7cfc9db5-0925-4cab-a111-9ea52b9fdd83"
  GO_EA_SERVER_URL: "https://cd.mouse.center:1443/go"
  AGENT_AUTO_REGISTER_ENVIRONMENTS: "k8s"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cd
  name: gocd-agent-java17
  labels:
    app: gocd-agent-java17
spec:
  selector:
    matchLabels:
      app: gocd-agent-java17
  replicas: 4
  template:
    metadata:
      name: gocd-agent-java17
      namespace: cd
      labels:
        app: gocd-agent-java17
    spec:
      containers:
        - name: gocd-agent-java17
          image: registry.mouse.center:1443/gocd-agent-java-node-docker:java17_gradle7.2
          env:
            - name: AGENT_AUTO_REGISTER_RESOURCES
              value: java17,node
          envFrom:
            - configMapRef:
                name: gocd-agent-config
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: dockersock
            - mountPath: /root/.ssh
              name: ssh
              subPath: .ssh
            - mountPath: /root/.docker
              name: docker-config
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-config
          hostPath:
            path: /root/.docker
        - name: ssh
          nfs:
            server: nas
            path: /volume2/k8s/gocd/go

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gocd-agent-kubectl
  namespace: cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gocd-agent-kubectl
  template:
    metadata:
      namespace: cd
      name: gocd-agent-kubectl
      labels:
        app: gocd-agent-kubectl
    spec:
      containers:
        - name: gocd-agent-kubectl
          image: registry.mouse.center:1443/gocd-agent-kubectl
          env:
            - name: AGENT_AUTO_REGISTER_RESOURCES
              value: kubectl
          envFrom:
            - configMapRef:
                name: gocd-agent-config
          volumeMounts:
            - mountPath: /root/.kube/config
              name: gocd-agent-config
              subPath: config
      volumes:
        - name: gocd-agent-config
          secret:
            secretName: gocd-agent-kubectl-secret