apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-centos7
  namespace: cd
  labels:
    app: gocd-agent
spec:
  containers:
    - name: gocd-agent-container
      image: docker-repository.mouse.center:1443/gocd-agent-java14-node-docker
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /root/.ssh
          name: ssh
          subPath: .ssh
        - mountPath: /root/.gradle
          name: gradle-cache
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: gradle-cache
      hostPath:
        path: /root/.gradle
    - name: ssh
      persistentVolumeClaim:
        claimName: gohome-pvc
