apiVersion: v1
kind: Pod
metadata:
  name: goce-agent-kubectl
  namespace: cd
  labels:
    k8s-app: gocd-agent-kubectl
spec:
  containers:
    - name: gocd-agent-kubectl
      image: registry.mouse.center:1443/gocd-agent-kubectl
      volumeMounts:
        - mountPath: /root/.kube/config
          name: gocd-agent-config
          subPath: config
  volumes:
    - name: gocd-agent-config
      secret:
        secretName: gocd-agent-kubectl-secret
