kind: PersistentVolume
apiVersion: v1
metadata:
  name: gocd-agent-pv
  namespace: cd
  labels:
    pv: gocd-agent-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: 192.168.20.5
    path: /volume1/k8s/gocd/go/.ssh
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: cd
  name: gocd-agent-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      pv: gocd-agent-pv
