apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  namespace: cd
  labels:
    k8s-app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nexus3
  template:
    metadata:
      labels:
        k8s-app: nexus3
      namespace: cd
      name: nexus3
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: nexus3
          image: sonatype/nexus3:3.33.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: web
              protocol: TCP
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 15
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 15
      volumes:
        - name: nexus-data
          nfs:
            path: /volume2/k8s/nexus
            server: nas
---
apiVersion: v1
kind: Service
metadata:
  name: nexus3
  namespace: cd
  labels:
    k8s-app: nexus3
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8081
  selector:
    k8s-app: nexus3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus3-ingress
  namespace: cd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: 10240M
spec:
  rules:
    - host: registry.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus3
                port:
                  number: 80
