apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-12306
  namespace: app
  labels:
    k8s-app: app-12306
spec:
  selector:
    matchLabels:
      k8s-app: app-12306
  replicas: 1
  template:
    metadata:
      namespace: app
      name: app-12306
      labels:
        k8s-app: app-12306
    spec:
      containers:
        - name: 12306-code-server
          image: docker-repository.mouse.center:1443/yinaoxiong/12306_code_server
          ports:
            - containerPort: 80
              name: api
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          env:
            - name: WORKERS
              value: '1'
            - name: PYTHONUNBUFFERED
              value: '1'
        - name: 12306-server
          image: docker-repository.mouse.center:1443/12306
          volumeMounts:
            - mountPath: /usr/src/app/TickerConfig.py
              name: ticker-config
              subPath: TickerConfig.py
      volumes:
        - name: ticker-config
          configMap:
            name: config-map-12306
---
kind: Service
apiVersion: v1
metadata:
  name: app-12306
  namespace: app
  labels:
    k8s-app: app-12306
spec:
  ports:
    - port: 80
      name: code-api
      targetPort: 80
  selector:
    k8s-app: app-12306
