kind: Pod
apiVersion: v1
metadata:
  name: jd-assistant
  namespace: app
  labels:
    k8s-app: jd-assistant
spec:
  containers:
    - name: jd-assistant
      image: docker-repository.mouse.center:1443/jd-assistant
      volumeMounts:
        - mountPath: /tmp
          name: main-py
      command: ["/bin/sh", "ls", "-l", "/tmp"]
  volumes:
    - name: main-py
      configMap:
        name: jd-assistant-cfg
        items:
          - key: main.py
            path: main.py
  nodeSelector:
    beta.kubernetes.io/os: linux
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jd-assistant-cfg
  namespace: app
data:
  main.py: |-
    from jd_assistant import Assistant

    if __name__ == '__main__':
        sku_ids = '100015042086'
        asst = Assistant()
        asst.login_by_QRcode()
        asst.add_item_to_cart(sku_ids)
        asst.exec_seckill_by_time(sku_ids=sku_ids, buy_time='2021-01-12 12:00:00.000', retry=10, interval=0.01)
