apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: builder
  labels:
    storageos.com/replicas: "1"
spec:
  storageClassName: "fast"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi