apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  namespace: builder
  labels:
    k8s-app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nexus3
  template:
    metadata:
      labels:
        k8s-app: nexus3
      namespace: builder
      name: nexus3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: web
              protocol: TCP
            - containerPort: 5000
              name: docker-proxy
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 6
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus3
  namespace: builder
  labels:
    k8s-app: nexus3
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8081
    - port: 81
      name: docker-repository
      targetPort: 5000
  selector:
    k8s-app: nexus3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus3-ingress
  namespace: builder
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  rules:
    - host: nexus.k8s.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus3
                port:
                  number: 80
    - host: docker-repository.k8s.mouse.center
      http:
        paths:
          - backend:
              service:
                name: nexus3
                port:
                  number: 81
            path: /
            pathType: Prefix