kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-pv
  namespace: builder
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: 192.168.20.5
    path: /volume1/k8s/nexus3