apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: es
  labels:
    app: es
spec:
  selector:
    app: es
  ports:
    - port: 80
      targetPort: 9200
      protocol: TCP
      name: api

---
kind: Service
apiVersion: v1
metadata:
  namespace: es
  name: es-cluster
  labels:
    app: es
spec:
  selector:
    app: es
  ports:
    - port: 9300
      name: cluster
      protocol: TCP

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: es-cluster-cfg
  namespace: es
data:
  elasticsearch.yml: |
    cluster.name: "es-cluster"
    node.name: "${POD_NAME}"
    network.host: 0.0.0.0
    discovery.seed_hosts: "es-cluster"
    cluster.initial_master_nodes: "es-0,es-1,es-2"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: es
  labels:
    app: es
spec:
  replicas: 3
  serviceName: es
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: registry.mouse.center:1443/elasticsearch:7.12.1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          volumeMounts:
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: ${POD_NAME}
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-config
          configMap:
            name: es-cluster-cfg
        - name: es-0
          nfs:
            path: /mnt/Database/k8s/elasticsearch/es-0
            server: nas
        - name: es-1
          nfs:
            path: /mnt/Database/k8s/elasticsearch/es-1
            server: nas
        - name: es-2
          nfs:
            path: /mnt/Database/k8s/elasticsearch/es-2
            server: nas
