apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: es
  labels:
    app: es
spec:
  selector:
    app: es
  ports:
    - port: 80
      targetPort: 9200
      protocol: TCP
      name: api

---
kind: Service
apiVersion: v1
metadata:
  namespace: es
  name: es-cluster
  labels:
    app: es
spec:
  selector:
    app: es
  ports:
    - port: 9300
      name: cluster
      protocol: TCP

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: es-cluster-cfg
  namespace: es
data:
  "cluster.name": "es-cluster"
  "network.host": 0.0.0.0
  "discovery.seed_hosts": "es-cluster"
  "cluster.initial_master_nodes": "es-0,es-1,es-2"
  "ES_JAVA_OPTS": "-Xms512m -Xmx512m"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: es-0
  namespace: es
spec:
  selector:
    matchLabels:
      es: es-0
  template:
    metadata:
      namespace: es
      name: es-0
      labels:
        app: es
        es: es-0
    spec:
      containers:
        - name: es-0
          image: registry.mouse.center:1443/elasticsearch:7.12.1
          command:
            - /bin/sh
          args:
            - -c
            - "sysctl -w vm.max_map_count=262144"
          env:
            - name: "node.name"
              value: "es-0"
          envFrom:
            - configMapRef:
                name: es-cluster-cfg
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-0
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
      volumes:
        - name: es-0
          nfs:
            path: /mnt/Database/k8s/elasticsearch/es-0
            server: nas

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: es-1
  namespace: es
spec:
  selector:
    matchLabels:
      es: es-1
  template:
    metadata:
      namespace: es
      name: es-1
      labels:
        app: es
        es: es-1
    spec:
      containers:
        - name: es-1
          image: registry.mouse.center:1443/elasticsearch:7.12.1
          command:
            - /bin/sh
          args:
            - -c
            - "sysctl -w vm.max_map_count=262144"
          env:
            - name: "node.name"
              value: "es-1"
          envFrom:
            - configMapRef:
                name: es-cluster-cfg
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-1
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
      volumes:
        - name: es-1
          nfs:
            path: /mnt/Database/k8s/elasticsearch/es-1
            server: nas

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: es-2
  namespace: es
spec:
  selector:
    matchLabels:
      es: es-2
  template:
    metadata:
      namespace: es
      name: es-2
      labels:
        app: es
        es: es-2
    spec:
      containers:
        - name: es-2
          image: registry.mouse.center:1443/elasticsearch:7.12.1
          command:
            - /bin/sh
          args:
            - -c
            - "sysctl -w vm.max_map_count=262144"
          env:
            - name: "node.name"
              value: "es-2"
          envFrom:
            - configMapRef:
                name: es-cluster-cfg
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-2
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
      volumes:
        - name: es-2
          nfs:
            path: /mnt/Database/k8s/elasticsearch/es-2
            server: nas
