---
apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    k8s-app: mongo
---
kind: Pod
apiVersion: v1
metadata:
  name: mongo-0
  namespace: db
  labels:
    k8s-app: mongo
spec:
  containers:
    - name: mongo
      image: docker-repository.mouse.center:1443/mongo:4.4.3
      command:
        - mongod
        - "--replSet"
        - rs0
        - "--port"
        - '27017'
        - "--bind_ip"
        - "0.0.0.0"
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongo-0-storage
  volumes:
    - name: mongo-0-storage
      nfs:
        path: /volume1/k8s/db/mongo-0
        server: nas.lan
---
kind: Pod
apiVersion: v1
metadata:
  name: mongo-1
  namespace: db
  labels:
    k8s-app: mongo
spec:
  containers:
    - name: mongo
      image: docker-repository.mouse.center:1443/mongo:4.4.3
      command:
        - mongod
        - "--replSet"
        - rs0
        - "--port"
        - '27017'
        - "--bind_ip"
        - "0.0.0.0"
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongo-1-storage
  volumes:
    - name: mongo-1-storage
      nfs:
        path: /volume1/k8s/db/mongo-1
        server: nas.lan
---
kind: Pod
apiVersion: v1
metadata:
  name: mongo-2
  namespace: db
  labels:
    k8s-app: mongo
spec:
  containers:
    - name: mongo
      image: docker-repository.mouse.center:1443/mongo:4.4.3
      command:
        - mongod
        - "--replSet"
        - rs0
        - "--port"
        - '27017'
        - "--bind_ip"
        - "0.0.0.0"
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongo-2-storage
  volumes:
    - name: mongo-2-storage
      nfs:
        path: /volume1/k8s/db/mongo-2
        server: nas.lan
---
