---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: db
  name: mongo-0
  labels:
    k8s-app: mongo-0
spec:
  selector:
    matchLabels:
      k8s-app: mongo-0
  template:
    metadata:
      labels:
        k8s-app: mongo-0
      name: mongo-0
      namespace: db
    spec:
      containers:
        - name: registry.mouse.center:1443/mongo:4.4.3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--port"
            - '27017'
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-0-data
      volumes:
        - name: mongo-0-data
          nfs:
            path: /mnt/Database/k8s/mongo/0
            server: nas
---
apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: mongo-0
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    k8s-app: mongo-0

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: db
  name: mongo-1
  labels:
    k8s-app: mongo-1
spec:
  selector:
    matchLabels:
      k8s-app: mongo-1
  template:
    metadata:
      labels:
        k8s-app: mongo-1
      name: mongo-1
      namespace: db
    spec:
      containers:
        - name: registry.mouse.center:1443/mongo:4.4.3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--port"
            - '27017'
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-1-data
      volumes:
        - name: mongo-1-data
          nfs:
            path: /mnt/Database/k8s/mongo/1
            server: nas
---
apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: mongo-1
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    k8s-app: mongo-1

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: db
  name: mongo-2
  labels:
    k8s-app: mongo-2
spec:
  selector:
    matchLabels:
      k8s-app: mongo-2
  template:
    metadata:
      labels:
        k8s-app: mongo-2
      name: mongo-2
      namespace: db
    spec:
      containers:
        - name: registry.mouse.center:1443/mongo:4.4.3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--port"
            - '27017'
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-2-data
      volumes:
        - name: mongo-2-data
          nfs:
            path: /mnt/Database/k8s/mongo/2
            server: nas
---
apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: mongo-2
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    k8s-app: mongo-2
