---
apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    k8s-app: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: db
  labels:
    k8s-app: mongo
spec:
  selector:
    matchLabels:
      k8s-app: mongo
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      name: mongo
      namespace: db
      labels:
        k8s-app: mongo
    spec:
      containers:
        - name: mongo
          image: registry.mouse.center:1443/mongo:4.4.3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--port"
            - '27017'
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "nfs-sc"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi


---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: db
  name: mongo-0-pv
  labels:
    pv: mongo-0-pv
spec:
  nfs:
    path: /mnt/Database/k8s/mongo/mongo-0
    server: nas
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-0-pvc
  namespace: db
spec:
  selector:
    matchLabels:
      pv: mongo-0-pv
  accessModes:
    - ReadWriteOnce
