apiVersion: v1
kind: Service
metadata:
  name: mongo-replication
  labels:
    db: mongo-replication
spec:
  selector:
    db: mongo-replication
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: db
  name: mongo-replication
  labels:
    db: mongo-replication
spec:
  selector:
    matchLabels:
      db: mongo-replication
  serviceName: mongo-replication
  replicas: 3
  template:
    metadata:
      name: mongo-replication
      namespace: db
      labels:
        db: mongo-replication
    spec:
      containers:
        - name: mongo
          image: registry.mouse.center:1443/mongo:4.4.3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--port"
            - '27017'
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-replication-storage
  volumeClaimTemplates:
    - metadata:
        name: mongo-replication-storage
      spec:
        storageClassName: "nfs-sc"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
