apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db
  labels:
    db: mysql
spec:
  selector:
    db: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-data-pv
  namespace: db
  labels:
    pv: mysql-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/k8s/mysql/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-pvc
  namespace: db
spec:
  selector:
    matchLabels:
      pv: mysql-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: db
  name: mysql
  labels:
    db: mysql
spec:
  selector:
    matchLabels:
      db: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      name: mysql
      namespace: db
      labels:
        db: mysql
    spec:
      containers:
        - name: mysql
          image: registry.mouse.center:1443/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secert
          ports:
            - containerPort: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
