apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db
  labels:
    db: mysql
spec:
  selector:
    db: mysql
  ports:
    - port: 3306
      targetPort: 3306

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: db
  name: mysql
  labels:
    db: mysql
spec:
  selector:
    matchLabels:
      db: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      name: mysql
      namespace: db
      labels:
        db: mysql
    spec:
      containers:
        - name: mysql
          image: registry.mouse.center:1443/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secert
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
      volumes:
        - name: data
          nfs:
            path: /mnt/Database/k8s/mysql/data
            server: nas
