apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db
  labels:
    db: mysql
spec:
  selector:
    db: mysql
  ports:
    - port: 3306
      name: mysql
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-cnf-cfg
  namespace: db
data:
  mysql.cnf: |
    [mysqld]
    port = 3306
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    secure-file-priv= NULL
    back_log = 600
    max_connections = 1000
    max_connect_errors = 6000
    open_files_limit = 65535
    table_open_cache = 128
    max_allowed_packet = 4M
    binlog_cache_size = 1M
    max_heap_table_size = 8M
    tmp_table_size = 16M
    read_buffer_size = 2M
    read_rnd_buffer_size = 8M
    sort_buffer_size = 8M
    join_buffer_size = 8M
    thread_cache_size = 16
    query_cache_size = 8M
    query_cache_limit = 2M
    key_buffer_size = 4M
    ft_min_word_len = 4
    transaction_isolation = REPEATABLE-READ
    slow_query_log = 1
    long_query_time = 1
    slow_query_log_file = /var/log/mysql/slow.log
    default-storage-engine = InnoDB
    innodb_file_per_table = 1
    innodb_open_files = 500
    innodb_buffer_pool_size = 1G
    innodb_write_io_threads = 4
    innodb_read_io_threads = 4
    innodb_thread_concurrency = 0
    innodb_purge_threads = 1
    innodb_flush_log_at_trx_commit = 2
    innodb_log_buffer_size = 2M
    innodb_log_file_size = 32M
    innodb_log_files_in_group = 3
    innodb_max_dirty_pages_pct = 90
    innodb_lock_wait_timeout = 120
    bulk_insert_buffer_size = 8M
    myisam_sort_buffer_size = 8M

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: db
  name: mysql
  labels:
    db: mysql
spec:
  selector:
    matchLabels:
      db: mysql
  replicas: 1
  template:
    metadata:
      name: mysql
      namespace: db
      labels:
        db: mysql
    spec:
      containers:
        - name: mysql
          image: registry.mouse.center:1443/mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secert
          ports:
            - containerPort: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
#            - mountPath: /etc/mysql/conf.d/mysql.cnf
#              name: mysql-cnf
#              subPath: mysql.cnf
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 6Gi
      volumes:
        - name: mysql-data
          nfs:
            path: /mnt/Database/k8s/mysql/data
            server: nas
        - name: mysql-cnf
          configMap:
            name: mysql-cnf-cfg
