apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db
  labels:
    db: mysql
spec:
  selector:
    db: mysql
  ports:
    - port: 3306
      name: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: db
  name: mysql
  labels:
    db: mysql
spec:
  selector:
    matchLabels:
      db: mysql
  replicas: 1
  template:
    metadata:
      name: mysql
      namespace: db
      labels:
        db: mysql
    spec:
      containers:
        - name: mysql
          image: registry.mouse.center:1443/mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secert
#          livenessProbe:
#            tcpSocket:
#              port: 3306
#            initialDelaySeconds: 60
#            periodSeconds: 20
#            failureThreshold: 6
#          readinessProbe:
#            tcpSocket:
#              port: 3306
#            initialDelaySeconds: 60
#            periodSeconds: 20
#            failureThreshold: 6
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 6Gi
      volumes:
        - name: mysql-data
          nfs:
            path: /mnt/Database/k8s/mysql/data
            server: nas
