apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: redis
  labels:
    db: redis
spec:
  selector:
    db: redis
  ports:
    - port: 6379
      targetPort: 6379

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis
  namespace: db
  labels:
    db: redis
spec:
  selector:
    matchLabels:
      db: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      namespace: db
      name: redis
      labels:
        db: redis
    spec:
      containers:
        - name: redis
          image: registry.mouse.center:1443/redis
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 6
