apiVersion: v1
kind: Service
metadata:
  name: cloud
  namespace: tool
  labels:
    app: cloud
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cloud
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-env-cfg
  namespace: tool
data:
  MYSQL_PASSWORD: "970210"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  MYSQL_HOST: "mysql.db"
  REDIS_HOST: "redis.db"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-pv
  namespace: tool
  labels:
    pv: cloud-pv
spec:
  capacity:
    storage: 10240Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/k8s/cloud
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloud-pvc
  namespace: tool
spec:
  selector:
    matchLabels:
      pv: cloud-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10240Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-user-pv
  namespace: tool
  labels:
    pv: cloud-user-pv
spec:
  capacity:
    storage: 10240Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/user

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloud-user-pvc
  namespace: tool
spec:
  selector:
    matchLabels:
      pv: cloud-user-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10240Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-video-pv
  namespace: tool
  labels:
    pv: cloud-video-pv
spec:
  capacity:
    storage: 10240Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/video

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloud-video-pvc
  namespace: tool
spec:
  selector:
    matchLabels:
      pv: cloud-video-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10240Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-share-pv
  namespace: tool
  labels:
    pv: cloud-share-pv
spec:
  capacity:
    storage: 10240Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/share

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloud-share-pvc
  namespace: tool
spec:
  selector:
    matchLabels:
      pv: cloud-share-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10240Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-music-pv
  namespace: tool
  labels:
    pv: cloud-music-pv
spec:
  capacity:
    storage: 10240Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: nas
    path: /mnt/Database/music

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloud-music-pvc
  namespace: tool
spec:
  selector:
    matchLabels:
      pv: cloud-music-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10240Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-crontab-cfg
  namespace: tool
data:
  www-data: |
    */5  *  *  *  * php -f /var/www/html/cron.php
    */1  *  *  *  * php -f /var/www/html/occ files:scan -p /var/www/html/data/__groupfolders/
---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: tool
  name: cloud
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      name: cloud
      namespace: tool
      labels:
        app: cloud
    spec:
      containers:
        - name: nextcloud
          image: registry.mouse.center:1443/nextcloud:fpm-alpine
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          ports:
            - containerPort: 80
              name: web
          #          livenessProbe:
          #            tcpSocket:
          #              port: 80
          #            initialDelaySeconds: 60
          #            periodSeconds: 20
          #            failureThreshold: 6
          #          readinessProbe:
          #            tcpSocket:
          #              port: 80
          #            initialDelaySeconds: 60
          #            periodSeconds: 20
          #            failureThreshold: 6
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
            - mountPath: /var/www/html/data
              name: user
            - mountPath: /var/www/html/data/__groupfolders/1
              name: video
            - mountPath: /var/www/html/data/__groupfolders/2
              name: share
            - mountPath: /var/www/html/data/__groupfolders/3
              name: music
            - mountPath: /var/spool/cron/crontabs/www-data
              name: crontab
              subPath: www-data
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: cloud-pvc
        - name: user
          persistentVolumeClaim:
            claimName: cloud-user-pvc
        - name: video
          persistentVolumeClaim:
            claimName: cloud-video-pvc
        - name: share
          persistentVolumeClaim:
            claimName: cloud-share-pvc
        - name: music
          persistentVolumeClaim:
            claimName: cloud-music-pvc
        - name: crontab
          configMap:
            name: cloud-crontab-cfg
---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cloud-ingress
  namespace: tool
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "102400M"
spec:
  rules:
    - host: cloud.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud
                port:
                  number: 80
