kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-env-cfg
  namespace: tool
data:
  MYSQL_PASSWORD: "970210"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  MYSQL_HOST: "mysql.db"
  REDIS_HOST: "redis.db"
  NEXTCLOUD_TRUSTED_DOMAINS: "cloud.mouse.center:1443"
  PHP_MEMORY_LIMIT: "2048M"
  PHP_UPLOAD_LIMIT: "10240M"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-crontab-cfg
  namespace: tool
data:
  www-data: |
  root: |
    */5  *  *  *  * php -f /var/www/html/cron.php
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud
  namespace: tool
spec:
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      namespace: tool
      name: cloud
      labels:
        app: cloud
    spec:
      containers:
        - name: app
          image: registry.mouse.center:1443/nextcloud:21.0.1-apache-full
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          volumeMounts:
            - mountPath: /var/www/html/config
              name: nextcloud
              subPath: config
            - mountPath: /var/www/html/custom_apps
              name: nextcloud
              subPath: custom_apps
            - mountPath: /var/www/html/themes
              name: nextcloud
              subPath: themes
            - mountPath: /var/www/html/data
              name: data
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 2Gi
        - name: cron
          image: registry.mouse.center:1443/nextcloud:21.0.1-apache-full
          command:
            - /bin/sh
          args:
            - -c
            - /cron.sh
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          volumeMounts:
            - mountPath: /var/www/html/config
              name: nextcloud
              subPath: config
            - mountPath: /var/www/html/custom_apps
              name: nextcloud
              subPath: custom_apps
            - mountPath: /var/www/html/themes
              name: nextcloud
              subPath: themes
            - mountPath: /var/www/html/data
              name: data
            - mountPath: /var/spool/cron/crontabs
              name: crontab
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: nextcloud
          nfs:
            path: /mnt/Database/k8s/cloud
            server: nas
        - name: data
          nfs:
            path: /mnt/Database/user
            server: nas
        - name: crontab
          configMap:
            name: cloud-crontab-cfg

---
apiVersion: v1
kind: Service
metadata:
  name: cloud
  namespace: tool
  labels:
    app: cloud
spec:
  selector:
    app: cloud
  ports:
    - port: 80
      name: web
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cloud-ingress
  namespace: tool
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "102400M"
spec:
  rules:
    - host: cloud.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud
                port:
                  name: web
