kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-crontab-cfg
  namespace: tool
data:
  www-data: |
    */5  *  *  *  * php -f /var/www/html/cron.php

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-env-cfg
  namespace: tool
data:
  MYSQL_PASSWORD: "970210"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  MYSQL_HOST: "mysql.db"
  REDIS_HOST: "redis.db"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud
  namespace: tool
spec:
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      namespace: tool
      name: cloud
      labels:
        app: cloud
    spec:
      containers:
        - name: app
          image: registry.mouse.center:1443/nextcloud:21.0.1-apache-full
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
            - mountPath: /var/www/html/data
              name: user
        - name: cron
          image: registry.mouse.center:1443/nextcloud:21.0.1-apache-full
          command:
            - /bin/sh
          args:
            - -c
            - /cron.sh
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
            - mountPath: /var/www/html/data
              name: user
            - mountPath: /var/spool/cron/crontabs/www-data
              name: crontab
              subPath: www-data
      volumes:
        - name: nextcloud
          nfs:
            path: /mnt/Database/k8s/cloud
            server: nas
        - name: user
          nfs:
            path: /mnt/Database/user
            server: nas
        - name: crontab
          configMap:
            name: cloud-crontab-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: cloud
  namespace: tool
  labels:
    app: cloud
spec:
  selector:
    app: cloud
  ports:
    - port: 80
      name: web
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cloud-ingress
  namespace: tool
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "102400M"
spec:
  rules:
    - host: cloud.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud
                port:
                  name: web
