kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-env-cfg
  namespace: tool
data:
  MYSQL_PASSWORD: "970210"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  MYSQL_HOST: "mysql.db"
  REDIS_HOST: "redis.db"
  NEXTCLOUD_TRUSTED_DOMAINS: "cloud.mouse.center:1443"
  PHP_MEMORY_LIMIT: "2048M"
  PHP_UPLOAD_LIMIT: "10240M"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-nginx-cfg
  namespace: tool
data:
  nginx.conf: |
    worker_processes auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        upstream php-handler {
            server cloud:9000;
        }

        server {
            listen 80;
            add_header Referrer-Policy "no-referrer" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-Download-Options "noopen" always;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Permitted-Cross-Domain-Policies "none" always;
            add_header X-Robots-Tag "none" always;
            add_header X-XSS-Protection "1; mode=block" always;
            fastcgi_hide_header X-Powered-By;
            root /var/www/html;

            location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
            }

            location = /.well-known/carddav {
                return 301 $scheme://$host:$server_port/remote.php/dav;
            }

            location = /.well-known/caldav {
                return 301 $scheme://$host:$server_port/remote.php/dav;
            }

            client_max_body_size 10G;
            fastcgi_buffers 64 4K;

            gzip on;
            gzip_vary on;
            gzip_comp_level 4;
            gzip_min_length 256;
            gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
            gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

            location / {
                rewrite ^ /index.php;
            }

            location ~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/ {
                deny all;
            }

            location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console) {
                deny all;
            }

            location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+)\.php(?:$|\/) {
                fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
                set $path_info $fastcgi_path_info;
                try_files $fastcgi_script_name =404;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $path_info;
                fastcgi_param modHeadersAvailable true;
                fastcgi_param front_controller_active true;
                fastcgi_pass php-handler;
                fastcgi_intercept_errors on;
                fastcgi_request_buffering off;
            }

            location ~ ^\/(?:updater|oc[ms]-provider)(?:$|\/) {
                try_files $uri/ =404;
                index index.php;
            }

            location ~ \.(?:css|js|woff2?|svg|gif|map)$ {
                try_files $uri /index.php$request_uri;
                add_header Cache-Control "public, max-age=15778463";
                add_header Referrer-Policy "no-referrer" always;
                add_header X-Content-Type-Options "nosniff" always;
                add_header X-Download-Options "noopen" always;
                add_header X-Frame-Options "SAMEORIGIN" always;
                add_header X-Permitted-Cross-Domain-Policies "none" always;
                add_header X-Robots-Tag "none" always;
                add_header X-XSS-Protection "1; mode=block" always;
                access_log off;
            }

            location ~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap|mp4|webm)$ {
                try_files $uri /index.php$request_uri;
                access_log off;
            }
        }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-php-fpm-cfg
  namespace: tool
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 120
    pm.start_servers = 12
    pm.min_spare_servers = 6
    pm.max_spare_servers = 18
    php_admin_value[memory_limit] = 512M

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-crontab-cfg
  namespace: tool
data:
  www-data: |
  root: |
    */5  *  *  *  * php -f /var/www/html/cron.php
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud
  namespace: tool
spec:
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      namespace: tool
      name: cloud
      labels:
        app: cloud
    spec:
      containers:
        - name: app
          image: registry.mouse.center:1443/nextcloud:21.0.1-fpm-full
          ports:
            - containerPort: 9000
              name: php-fpm
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          volumeMounts:
            - mountPath: /usr/local/etc/php-fpm.d/www.conf
              name: cloud-php-fpm-cfg
              subPath: www.conf
            - mountPath: /var/www/html
              name: html
            - mountPath: /var/www/html/config
              name: nextcloud
              subPath: config
            - mountPath: /var/www/html/custom_apps
              name: nextcloud
              subPath: custom_apps
            - mountPath: /var/www/html/themes
              name: nextcloud
              subPath: themes
#            - mountPath: /var/www/html/data
#              name: data
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 2Gi
        - name: cron
          image: registry.mouse.center:1443/nextcloud:21.0.1-fpm-full
          command:
            - /bin/sh
          args:
            - -c
            - /cron.sh
          envFrom:
            - configMapRef:
                name: cloud-env-cfg
          volumeMounts:
            - mountPath: /usr/local/etc/php-fpm.d/www.conf
              name: cloud-php-fpm-cfg
              subPath: www.conf
            - mountPath: /var/www/html
              name: html
            - mountPath: /var/www/html/config
              name: nextcloud
              subPath: config
            - mountPath: /var/www/html/custom_apps
              name: nextcloud
              subPath: custom_apps
            - mountPath: /var/www/html/themes
              name: nextcloud
              subPath: themes
#            - mountPath: /var/www/html/data
#              name: data
            - mountPath: /var/spool/cron/crontabs
              name: crontab
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        - name: web
          image: registry.mouse.center:1443/nginx
          ports:
            - containerPort: 80
              name: web
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: cloud-nginx-cfg
              subPath: nginx.conf
            - mountPath: /var/www/html
              name: html
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
      volumes:
        - name: nextcloud
          nfs:
            path: /mnt/Database/k8s/cloud
            server: nas
        - name: data
          nfs:
            path: /mnt/Database/user
            server: nas
        - name: html
          emptyDir:
            medium: Memory
        - name: crontab
          configMap:
            name: cloud-crontab-cfg
        - name: cloud-nginx-cfg
          configMap:
            name: cloud-nginx-cfg
        - name: cloud-php-fpm-cfg
          configMap:
            name: cloud-php-fpm-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: cloud
  namespace: tool
  labels:
    app: cloud
spec:
  selector:
    app: cloud
  ports:
    - port: 80
      name: web
    - port: 9000
      name: php-fpm
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cloud-ingress
  namespace: tool
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "102400M"
spec:
  rules:
    - host: cloud.mouse.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud
                port:
                  name: web
